services:
  - type: web
    name: cropdisease-app
    env: python
    region: oregon
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"  # OR "python app.py"
    plan: free
